"""Changes in API_Token

Revision ID: 101d0337c67b
Revises: 98a008e79e0b
Create Date: 2024-10-05 16:47:17.003898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '101d0337c67b'
down_revision = '98a008e79e0b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_tokens', sa.Column('push_device_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_tokens', 'push_device_id')
    # ### end Alembic commands ###
