"""added user and api_token tables

Revision ID: 8ddba43b1326
Revises: 09f9d28df736
Create Date: 2024-10-05 14:00:29.299618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ddba43b1326'
down_revision = '09f9d28df736'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
